### ISSUE TITLE
No error message displayed when parsing png image sometimes.

### ISSUE THREAD

**Issue by gauravraj** [zhso/jpeg-exif#1]
I'm using exifParser2.parseSync(imageFilePath) to parse metadata in my nodejs project. It parses jpeg files perfectly. But when I pass png image to this function it gives me error sometimes while other times it gives me previously parsed values. When I restarted my application and passed a png image to this function it displayed error as expected. But if I pass jpg images to it before passing a png image, it returns the metadata of the previously parsed value.

**Comment by zhso** [comment]
a global variable status was unreset, tag 1.0.1 fixed
