### ISSUE TITLE
Loses DMS coordinate minutes and second

### ISSUE THREAD

**Issue by ragauskl** [zhso/jpeg-exif#14]
As you can see JPEG has DMS coordinates 
![image](https://user-images.githubusercontent.com/9280160/62536837-e6bedb80-b846-11e9-85ed-5d2515d6964c.png)

But when parsed, only degree values remain
```ts
import * as exif from 'jpeg-exif'
import { promisify } from 'util'

(async () => {
  const meta = await promisify(exif.parse)(<file path>)
  // Debug info displayed in image below
})()
```
 
![image](https://user-images.githubusercontent.com/9280160/62537194-c0e60680-b847-11e9-9e45-a82012225391.png)

**Comment by zhso** [comment]
Fixed, now the gps longitude and latitude are return origin data in array of numbers.
